#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
#. /etc/X11/Xsession

# Spidal add
# Disable any form of screen saver / screen blanking / power management
xset s off
xset s noblank
xset -dpms

# Allow quitting the X server with CTRL-ATL-Backspace
setxkbmap -option terminate:ctrl_alt_bksp

/home/pi/spidal/programs/bin/app/spidal

#chromium-browser --noerrdialogs --start-fullscreen  --start-maximized --disable-notifications --disable-infobars --kiosk http://172.24.1.1

#xinit /usr/bin/chromium-browser --no-sandbox --no-first-run --window-size=1024,600 --noerrdialogs --start-fullscreen  --start-maximized --disable-notifications --disable-infobars --kiosk --incognito http://172.24.1.1 -- -nocursor &
